import argparse
import csv
import os
import sys
from contextlib import contextmanager
from pathlib import Path

import numpy as np
try:
    from tqdm import tqdm
except ImportError:
    tqdm = None

CURRENT_DIR = Path(__file__).resolve().parent
ROOT_DIR = CURRENT_DIR.parent
sys.path.append(str(ROOT_DIR))

from data_utils.geometry.inout import write_ply_o3d
from extention.gpcc_geo import gpcc_decode, gpcc_encode


DEFAULT_QUANT_MAP = (
    '1/64,1/64;1/64,3/256;1/64,2/256;1/64,1/256;'
    '1/64,1.5/512;1/64,1/512;1/64,1/2048'
)
# Masks generated by OpenPCDet/tools/generate_masks.py are binary:
# 0 = background, 1 = foreground.
FG_CLASSES = [1]


@contextmanager
def suppress_stderr():
    fd = sys.stderr.fileno()
    saved_fd = os.dup(fd)
    devnull = os.open(os.devnull, os.O_WRONLY)
    os.dup2(devnull, fd)
    try:
        yield
    finally:
        os.dup2(saved_fd, fd)
        os.close(devnull)
        os.close(saved_fd)


def parse_scale(value):
    value = str(value).strip()
    if '/' in value:
        numerator, denominator = value.split('/', 1)
        return float(numerator) / float(denominator)
    return float(value)


def parse_quant_map(text):
    combos = []
    for item in str(text).split(';'):
        item = item.strip()
        if not item:
            continue
        fg, bg = [part.strip() for part in item.split(',', 1)]
        combos.append((parse_scale(fg), parse_scale(bg)))
    if not combos:
        raise ValueError('--quant_map must contain at least one fg,bg pair')
    return combos


def collect_files(testdata, split_file):
    testdata = Path(testdata)
    if testdata.is_file():
        return [testdata]
    if split_file:
        with open(split_file, 'r') as f:
            frame_ids = [line.strip() for line in f if line.strip()]
        return [testdata / f'{frame_id}.bin' for frame_id in frame_ids if (testdata / f'{frame_id}.bin').exists()]
    return sorted(testdata.rglob('*.bin'))


def read_kitti_bin(path):
    points = np.fromfile(str(path), dtype=np.float32).reshape(-1, 4)
    return points[:, :3]


def read_seg_times(path):
    if not path or not Path(path).exists():
        return {}
    times = {}
    with open(path, newline='') as f:
        for row in csv.DictReader(f):
            frame_id = row.get('frame_id') or row.get('filename')
            if frame_id:
                times[frame_id] = float(row.get('seg_time') or 0.0)
    return times


def encode_subset(frame_id, name, coords, scale, tmp_dir, cfg_path):
    if len(coords) == 0:
        return {'bits': 0, 'enc_time': 0.0, 'dec_time': 0.0}

    ref_ply = tmp_dir / f'{frame_id}_{name}_ref.ply'
    bitstream = tmp_dir / f'{frame_id}_{name}_scale_{scale:.12g}.bin'
    dec_ply = tmp_dir / f'{frame_id}_{name}_scale_{scale:.12g}_dec.ply'

    write_ply_o3d(str(ref_ply), coords, normal=True, knn=16)
    try:
        with suppress_stderr():
            enc_log = gpcc_encode(str(ref_ply), str(bitstream), posQuantscale=scale, cfgdir=str(cfg_path))
            dec_log = gpcc_decode(str(bitstream), str(dec_ply))
        return {
            'bits': bitstream.stat().st_size * 8 if bitstream.exists() else 0,
            'enc_time': float(enc_log.get('Processing time (wall)', 0.0)) if isinstance(enc_log, dict) else 0.0,
            'dec_time': float(dec_log.get('Processing time (wall)', 0.0)) if isinstance(dec_log, dict) else 0.0,
        }
    finally:
        for path in (ref_ply, bitstream, dec_ply):
            if path.exists():
                path.unlink()


def main():
    parser = argparse.ArgumentParser(description='Measure Split-GPCC bpp and time from cached foreground/background masks.')
    parser.add_argument('--testdata', required=True, help='KITTI velodyne directory or one .bin file')
    parser.add_argument('--split_file', default=None, help='Optional ImageSets split file')
    parser.add_argument('--mask_dir', required=True, help='Directory containing <frame_id>.npy segmentation masks')
    parser.add_argument('--seg_time_csv', default=None, help='CSV containing frame_id,seg_time')
    parser.add_argument('--quant_map', default=DEFAULT_QUANT_MAP, help='Semicolon-separated fg,bg quantization pairs')
    parser.add_argument('--results', default='GPCC/results_split', help='Output result directory')
    parser.add_argument('--tmp_dir', default='GPCC/tmp_split', help='Temporary file directory')
    parser.add_argument('--cfg', default='extention/kitti.cfg', help='G-PCC cfg file')
    args = parser.parse_args()

    combos = parse_quant_map(args.quant_map)
    result_dir = Path(args.results)
    tmp_dir = Path(args.tmp_dir)
    mask_dir = Path(args.mask_dir)
    cfg_path = Path(args.cfg).resolve()
    result_dir.mkdir(parents=True, exist_ok=True)
    tmp_dir.mkdir(parents=True, exist_ok=True)

    files = collect_files(args.testdata, args.split_file)
    if not files:
        raise FileNotFoundError('No input .bin files found for Split-GPCC measurement.')
    seg_times = read_seg_times(args.seg_time_csv)

    detail_rows = []
    progress = tqdm(total=len(files) * len(combos), desc='Split-GPCC', unit='job') if tqdm else None
    try:
        for bin_path in files:
            frame_id = bin_path.stem
            mask_path = mask_dir / f'{frame_id}.npy'
            if not mask_path.exists():
                raise FileNotFoundError(f'Missing mask: {mask_path}')

            coords_raw = read_kitti_bin(bin_path)
            num_points = len(coords_raw)
            if num_points == 0:
                if progress:
                    progress.update(len(combos))
                continue

            labels = np.load(mask_path)[:num_points]
            fg_mask = np.isin(labels, FG_CLASSES)
            coords_mm = np.round(coords_raw.astype(np.float64) * 1000).astype(np.int32)
            coords_scaled = coords_mm - coords_mm.min(axis=0)
            coords_fg = coords_scaled[fg_mask]
            coords_bg = coords_scaled[~fg_mask]
            seg_time = float(seg_times.get(frame_id, 0.0))

            for rate_id, (scale_fg, scale_bg) in enumerate(combos):
                if progress:
                    progress.set_postfix(frame=frame_id, combo=rate_id)
                fg_stats = encode_subset(frame_id, f'fg_{rate_id}', coords_fg, scale_fg, tmp_dir, cfg_path)
                bg_stats = encode_subset(frame_id, f'bg_{rate_id}', coords_bg, scale_bg, tmp_dir, cfg_path)
                total_bits = fg_stats['bits'] + bg_stats['bits']
                fg_enc = fg_stats['enc_time']
                bg_enc = bg_stats['enc_time']
                gpcc_enc = fg_enc + bg_enc
                dec_time = fg_stats['dec_time'] + bg_stats['dec_time']
                detail_rows.append({
                    'filename': frame_id,
                    'rate_id': rate_id,
                    'combo_id': rate_id,
                    'posQ_fg': scale_fg,
                    'posQ_bg': scale_bg,
                    'posQuantscale': f'{scale_fg},{scale_bg}',
                    'scale': f'{scale_fg},{scale_bg}',
                    'num_points': num_points,
                    'fg_points': int(fg_mask.sum()),
                    'bg_points': int((~fg_mask).sum()),
                    'bits': total_bits,
                    'bpp': round(total_bits / num_points, 6),
                    'seg_time': round(seg_time, 6),
                    'fg_enc_time': round(fg_enc, 6),
                    'bg_enc_time': round(bg_enc, 6),
                    'gpcc_enc_time': round(gpcc_enc, 6),
                    'enc_time': round(seg_time + gpcc_enc, 6),
                    'dec_time': round(dec_time, 6),
                })
                if progress:
                    progress.update(1)
    finally:
        if progress:
            progress.close()

    detail_csv = result_dir / 'split_all_details.csv'
    fieldnames = [
        'filename', 'rate_id', 'combo_id', 'posQ_fg', 'posQ_bg', 'posQuantscale',
        'scale', 'num_points', 'fg_points', 'bg_points', 'bits', 'bpp',
        'seg_time', 'fg_enc_time', 'bg_enc_time', 'gpcc_enc_time', 'enc_time', 'dec_time'
    ]
    with open(detail_csv, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(detail_rows)

    grouped = {}
    for row in detail_rows:
        grouped.setdefault(row['rate_id'], []).append(row)

    avg_rows = []
    for rate_id in sorted(grouped):
        rows = grouped[rate_id]
        total_bits = sum(int(r['bits']) for r in rows)
        total_points = sum(int(r['num_points']) for r in rows)
        avg_rows.append({
            'rate_id': rate_id,
            'combo_id': rate_id,
            'posQ_fg': rows[0]['posQ_fg'],
            'posQ_bg': rows[0]['posQ_bg'],
            'posQuantscale': rows[0]['posQuantscale'],
            'scale': rows[0]['scale'],
            'num_frames': len(rows),
            'total_points': total_points,
            'total_bits': total_bits,
            'bpp': round(total_bits / total_points, 6) if total_points else 0.0,
            'seg_time': round(sum(float(r['seg_time']) for r in rows) / len(rows), 6),
            'fg_enc_time': round(sum(float(r['fg_enc_time']) for r in rows) / len(rows), 6),
            'bg_enc_time': round(sum(float(r['bg_enc_time']) for r in rows) / len(rows), 6),
            'gpcc_enc_time': round(sum(float(r['gpcc_enc_time']) for r in rows) / len(rows), 6),
            'enc_time': round(sum(float(r['enc_time']) for r in rows) / len(rows), 6),
            'dec_time': round(sum(float(r['dec_time']) for r in rows) / len(rows), 6),
        })

    avg_csv = result_dir / 'split_average_results.csv'
    with open(avg_csv, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=list(avg_rows[0].keys()) if avg_rows else [])
        writer.writeheader()
        writer.writerows(avg_rows)

    print(f'Detail CSV: {detail_csv}')
    print(f'Average CSV: {avg_csv}')


if __name__ == '__main__':
    main()
