#!/usr/bin/env python3
import argparse
import csv
from pathlib import Path

import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt


METHODS = {
    'Baseline G-PCC': {
        'color': '#ff7f0e',
        'marker': 'X',
        'linestyle': '--',
    },
    'Split-GPCC': {
        'color': '#1f77b4',
        'marker': 's',
        'linestyle': '-.',
    },
    'JUQP Router': {
        'color': '#2ca02c',
        'marker': 'o',
        'linestyle': '-',
    },
}


def parse_args():
    parser = argparse.ArgumentParser(description='Plot PSNR-bpp curves for three methods.')
    parser.add_argument(
        '--csv',
        default='point_pairs/psnr_bpp/all_methods_psnr_bpp_curve.csv',
        help='Combined PSNR-bpp CSV generated by compute_psnr_bpp_curves.py.',
    )
    parser.add_argument('--out_dir', default='plots', help='Directory for output figures.')
    parser.add_argument('--formats', default='png', help='Comma-separated formats, e.g. png,pdf.')
    parser.add_argument('--dpi', type=int, default=300)
    return parser.parse_args()


def read_csv(path):
    rows = []
    with open(path, newline='') as f:
        for row in csv.DictReader(f):
            rows.append(row)
    if not rows:
        raise ValueError(f'No rows found in {path}')
    return rows


def to_float(row, column):
    value = row.get(column, '')
    if value is None or value == '':
        return None
    return float(value)


def collect_points(rows, method):
    points = []
    for row in rows:
        if row.get('method') != method:
            continue
        bpp = to_float(row, 'bpp')
        psnr = to_float(row, 'psnr_p2point')
        if bpp is None or psnr is None:
            continue
        points.append((bpp, psnr))
    points.sort(key=lambda item: item[0])
    return points


def adaptive_ylim(curves):
    values = [y for points in curves for _, y in points]
    if not values:
        return None
    y_min = min(values)
    y_max = max(values)
    pad = max((y_max - y_min) * 0.08, 0.5) if y_min != y_max else 1.0
    return max(0, y_min - pad), y_max + pad


def main():
    args = parse_args()
    rows = read_csv(args.csv)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    formats = [fmt.strip().lstrip('.') for fmt in args.formats.split(',') if fmt.strip()]

    plt.figure(figsize=(8.5, 6))
    plotted = []
    for method, style in METHODS.items():
        points = collect_points(rows, method)
        if not points:
            continue
        x_vals = [x for x, _ in points]
        y_vals = [y for _, y in points]
        plt.plot(
            x_vals,
            y_vals,
            color=style['color'],
            marker=style['marker'],
            linestyle=style['linestyle'],
            markersize=6,
            linewidth=2.2,
            label=method,
        )
        plotted.append(points)

    if not plotted:
        raise ValueError(f'No plottable PSNR-bpp points found in {args.csv}')

    plt.xlabel('Bits Per Point (bpp)', fontsize=13)
    plt.ylabel('D1 PSNR (p2point, dB)', fontsize=13)
    plt.title('PSNR-bpp Curve', fontsize=15, pad=12)
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.legend(loc='best', fontsize=11)
    ylim = adaptive_ylim(plotted)
    if ylim is not None:
        plt.ylim(*ylim)
    plt.tight_layout()

    saved = []
    for fmt in formats:
        out_path = out_dir / f'psnr_bpp.{fmt}'
        plt.savefig(out_path, dpi=args.dpi, facecolor='white')
        saved.append(out_path)
    plt.close()

    print(f'[+] Saved {len(saved)} plot(s)')
    for path in saved:
        print(path)


if __name__ == '__main__':
    main()
