_BASE_CONFIG_: cfgs/kitti_models/pv_rcnn.yaml

DATA_CONFIG:
    _BASE_CONFIG_: ../../integrations/openpcdet/configs/dataset_configs/kitti_dataset_geometry.yaml
    DATA_PATH: '../data/kitti_fov'
    FOV_POINTS_ONLY: True
